function [path] = model2hdr(file, model, format)
%MODEL2HDR System model export to MyWay C# header-file.
% [path] = model2hdr(file, title, header, model)
% file      : header-file name      (string)
% model     : models matrix data    (structures-of-models)
% author    : Thomas Beauduin, University of Tokyo, 2015
%%%%%

% FILE: data header-file
fid = fopen(file,'w');
fprintf(fid,strcat('// STATE-SPACE PARAMETERS HEADER \n'));
fprintf(fid,strcat('// automatically generated by acqtools repository \n'));

if nargin < 3
    format = 'double';
end
format = [format,'\t'];

% MODELS: structures of system models
if isstruct(model), model_name = fieldnames(model);
else                model_name = {'model'};
end
for i=1:length(model_name)
    fprintf(fid,strcat('//',model_name{i},' model','\n'));
    if isstruct(model), sys = balreal(model.(model_name{i}));
    else                sys = balreal(model);
    end
    [matrix.A,matrix.B,matrix.C,matrix.D] = ssdata(sys);
    matrix_name = fieldnames(matrix);
    
    % MATRIX: state-space data matrix
    for j=1:length(matrix_name)
        matrix_size = size(matrix.(matrix_name{j}));
        str = char(strcat(format,matrix_name{j},model_name{i},...
                          '[',num2str(matrix_size(1)),']',...
                          '[',num2str(matrix_size(2)),']','\t='));
        for n=1:matrix_size(1)
            if n==1; str = strcat(str,'{\n \t{');
            else     str = strcat(str,'},\n \t{');
            end
            for m=1:matrix_size(2)
                if m==1; str = strcat(str,'%.15e');
                else     str = strcat(str,',%.15e');
                end
            end
        end
        str = strcat(str,'}\n \t};\n'); 
        data = [];
        for k=1:matrix_size(1)
            data = [data,matrix.(matrix_name{j})(k,:)];
        end
        fprintf(fid,str,data);
    end
    
    % VECTOR: state-space state vector
    matrix_size = size(matrix.(matrix_name{1}));
    str = char(strcat(format,'x',model_name{i},...
                      '[',num2str(matrix_size(1)),']',' \t={ \t'));
    for m=1:matrix_size(1)
        if m==1; str = strcat(str,'%.1e');
        else     str = strcat(str,',%.1e');
        end
    end
    str = strcat(str,'\t};\n'); 
    data = zeros(matrix_size(1),1);
    fprintf(fid,str,data);
    fprintf(fid,'\n');
end
fprintf(fid,strcat('// https://github.com/HoriFujimotoLab/AcqTools \n'));
fprintf(fid,strcat('// Thomas Beauduin, HFlab (University of Tokyo) \n'));
fclose(fid);
path = strcat(pwd,'\',file);
    
end